### ISSUE TITLE
Xcode static analyzer signals a memory leak issue

### ISSUE THREAD

**Issue by jeroenleenarts** [creachadair/imath#4]
When running static analysis on Xcode 5.1.1 I get a message that a memory issue might exist on the following line: https://github.com/creachadair/imath/blob/4d707e5ef22923ec230b8d5ed8c5879af8b62f03/imath.c#L449

Is this a real issue or is it safe to ignore?

**Comment by jeroenleenarts** [comment]
Looked into this.

The situation that would trigger this memory condition detected by the static analyser would be calling ```mp_int_div``` with a value of a larger then b, b being NULL and q and r having a value. But this is prevented by the guard on line 942:
```
CHECK(a != NULL && b != NULL && q != r);
```
I understand the guard here. But to stop the whining of the static analyser this construct seems to fix the warning:
```
CHECK(a != NULL && b != NULL && q != r);
if (a != NULL && b != NULL && q != r) {
      return MP_BADARG;
  }
```

(Basically it provides the static analyzer with a way out when the CHECK-ed condition occurs.)

What are your thoughts?

**Comment by creachadair** [comment]
I never did manage to convince Xcode to reproduce this, and enough time has passed that the versions of everything are all different now. For what it's worth I wasn't able to trigger any warnings on this code with valgrind.

If you do see it pop up again, please let me know; sorry I let it languish so long.
