### ISSUE TITLE
Grammar mistake in the code

### ISSUE THREAD

**Issue by michaelpq** [creachadair/imath#46]
Hello, there is a grammar mistake in this comment:
https://github.com/creachadair/imath/blob/01c0a40b18ef2761381a6e8848396ee52497f54c/imath.c#L2488
```
-   quotient digit. This makes our algorithm less efficient that Knuth because
+   quotient digit. This makes our algorithm less efficient than Knuth because
```

**Comment by creachadair** [comment]
Thanks for reporting, this is fixed in #47.
